{%- from 'reggie/map.jinja' import reggie with context -%}

export PYTHONSTARTUP="$HOME/.pythonstartup.py"
export PATH="{{ reggie.install_dir }}/env/bin:$PATH"

alias run_server='{{ reggie.install_dir }}/env/bin/python {{ reggie.install_dir }}/sideboard/run_server.py'

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

source {{ reggie.install_dir }}/env/bin/activate
